<?php
/**
 * Created by PhpStorm.
 * User: SKEPSIS-DEV40
 * Date: 3/13/2018
 * Time: 10:28 AM
 */

defined('_JEXEC') or die();

class ChartViewChart extends \Joomla\CMS\MVC\View\HtmlView
{
    protected $tableList;
    protected $columnsList;
    protected $tableName = null;

    protected $formTables = null;

    public function display($tpl = null)
    {
        $this->formTables = $this->get('Form');


        $jform = \Joomla\CMS\Factory::getApplication()->input->get('jform', array(), 'array');
        if(isset($jform['tablename'])) $this->tableName = $jform['tablename'];

        $model = $this->getModel();
        if($this->tableName) $this->columnsList = $model->getTableColumns($this->tableName);

        //$this->tableList = $model->getDatabaseTables();
        return parent::display($tpl); // TODO: Change the autogenerated stub
    }
}