<?php
/**
 * Created by PhpStorm.
 * User: SKEPSIS-DEV40
 * Date: 12/28/2017
 * Time: 2:28 PM
 */

defined('_JEXEC') or die();

class ChartViewChart extends \Joomla\CMS\MVC\View\HtmlView
{
    protected $resultList;

    public function display($tpl = null)
    {

        /*$this->model = \Joomla\CMS\MVC\Model\BaseDatabaseModel::getInstance('Chart', 'ChartModel');

        $app = \Joomla\CMS\Factory::getApplication();
        $start = $app->input->get('start', '');
        $end = $app->input->get('end', '');
        $job = 'get'.$app->input->get('job', 'All');

        $this->resultList = $this->model->$job($start, $end);*/

        $model = $this->getModel('Chart');
        $this->resultList = $model->getResult();

        return parent::display($tpl); // TODO: Change the autogenerated stub
    }
}